default: &DEFAULT
  num_data_workers: 1
  # model
  model: 'fno'
  depth: 5
  in_dim: 2
  out_dim: 1
  dropout: 0
  # data/domain
  Lx: !!float 1.0
  Ly: !!float 1.0
  nx: 256
  ny: 256
  # optimization
  weights: '/root/autodl-tmp/model_para/expts/ad-scale-adr0p2_1/ad2-4-attention/checkpoints/ckpt.tar'
  loss_style: 'mean'
  loss_func: 'mse'
  optimizer: 'adam'
  scheduler: 'none'
  lr: !!float 1.0
  max_epochs: 300
  max_cosine_lr_epochs: 300
  batch_size: 128
  # misc
  log_to_screen: !!bool True
  save_checkpoint: !!bool False
  seed: 3407
  plot_figs: !!bool False
  pack_data: !!bool False
  # Weights & Biases
  # Weights & Biases
  entity: 'your_wandb_entity'
  project: 'your_wandb_project'
  distill: !!bool False
  subsample: 1

advdiff: &advdiff
  <<: *DEFAULT
  batch_size: 128
  valid_batch_size: 128
  nx: 128
  ny: 128
  log_to_wandb: !!bool True
  save_checkpoint: !!bool True
  max_epochs: 300
  scheduler: 'cosine'
  plot_figs: !!bool True
  loss_style: 'sum'

  model: 'fno'
  layers: [64, 64, 64, 64, 64]
  modes1: [65, 65, 65, 65]
  modes2: [65, 65, 65, 65]
  fc_dim: 128

  in_dim: 6
  out_dim: 1
  mode_cut: 16
  embed_cut: 64
  fc_cut: 2

  optimizer: 'adam'

  lr: 1E-3
  pack_data: !!bool False

ad-scale-adr0p2_1: &ad_scale_0p2_1
  <<: *advdiff
  train_path:   '/root/autodl-tmp/data/ad/fine/ad2-4/8/_train_adr2.0_4.0_32k.h5'
  val_path:     '/root/autodl-tmp/data/ad/2-4-40960/_val_adr2.0_4.0_4k.h5'
  test_path:    '/root/autodl-tmp/data/ad/2-4-40960/_test_adr2.0_4.0_4k.h5'
  scales_path:  '/root/autodl-tmp/data/ad/0.2-2-8192/_train_adr0.2_2.0_scales.npy'
  batch_size: 8
  valid_batch_size: 7
  log_to_wandb: !!bool False
  mode_cut: 32
  embed_cut: 64
  fc_cut: 2
